<?php

namespace common\models;

use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%video}}".
 *
 * @property string $video_id
 * @property string $title
 * @property string|null $description
 * @property int|null $created_by
 *
 * @property User $createdBy
 */
class video extends \yii\db\ActiveRecord
{
    /**
     * @var \GuzzleHttp\Psr7\UploadedFile
     */
    public $video;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%video}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['video_id', 'title'], 'required'],
            [['description'], 'string'],
            [['created_by'], 'integer'],
            [['video_id'], 'string', 'max' => 16],
            [['title'], 'string', 'max' => 500],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'video_id' => 'Video ID',
            'title' => 'Title',
            'description' => 'Description',
            'created_by' => 'Created By',
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\UserQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\videoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\videoQuery(get_called_class());
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $isInsert = $this->isNewRecord;
        if($isInsert == true)
        {
            $this->video_id = Yii::$app->security->generateRandomString(10);
            $this->title = $this->video->name;

        }
        $videoPath = Yii::getAlias('@frontend/web/storage/videos/'.$this->video_id.'.mp4');
        $this->description = $videoPath;
        $saved = parent::save($runValidation, $attributeNames);
        if(!$saved)
        {
            return false;
        }

        if($isInsert)
        {
            if(!is_dir(dirname($videoPath)))
            {
                FileHelper::createDirectory(dirname($videoPath));
            }
            $this->video->saveAs($videoPath);

        }


        return true;  // TODO: Change the autogenerated stub
    }

}
